In [18]:
from sklearn.datasets import fetch_kddcup99
from sklearn.cluster import kmeans_plusplus
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from scipy.spatial.distance import cdist
import wkpp as wkpp 
import pandas as pd
import numpy as np
import cv2
import random
import warnings
warnings.filterwarnings("ignore")

image = cv2.imread('fruits.jpg')

# Check if the image was loaded successfully
if image is not None:
    # Convert the image to a NumPy array
    numpy_array = np.array(image)
							# Fetch kddcup99 
data = numpy_array	
print(data)

[[[150 125 123]
  [148 123 121]
  [135 110 108]
  ...
  [101  82  74]
  [ 92  73  65]
  [ 86  67  59]]

 [[150 125 123]
  [147 122 120]
  [138 113 111]
  ...
  [101  82  74]
  [ 93  74  66]
  [ 87  68  60]]

 [[149 124 122]
  [146 121 119]
  [142 117 115]
  ...
  [102  83  75]
  [ 97  78  70]
  [ 90  71  63]]

 ...

 [[128 115 117]
  [120 107 109]
  [100  87  89]
  ...
  [ 51  40  32]
  [ 52  41  33]
  [ 52  41  33]]

 [[126 113 115]
  [114 101 103]
  [100  87  89]
  ...
  [ 51  40  32]
  [ 53  42  34]
  [ 54  43  35]]

 [[121 108 110]
  [109  96  98]
  [102  89  91]
  ...
  [ 51  40  32]
  [ 53  42  34]
  [ 55  44  36]]]


In [19]:
						# Preprocess
data = image.reshape(-1, image.shape[-1])
data = data.astype(float)								# Preprocess
data = StandardScaler().fit_transform(data)				# Preprocess
print(data)

[[ 1.35199381  0.43978941  0.14211355]
 [ 1.31118479  0.40483309  0.11025952]
 [ 1.0459262   0.17761702 -0.0967917 ]
 ...
 [-0.66805241 -1.04585413 -1.30724497]
 [-0.6272434  -1.01089782 -1.27539094]
 [-0.58643438 -0.9759415  -1.24353691]]


In [20]:
print(pd.DataFrame(data))

               0         1         2
0       1.351994  0.439789  0.142114
1       1.311185  0.404833  0.110260
2       1.045926  0.177617 -0.096792
3       1.127544  0.282486 -0.001230
4       1.229567  0.369877  0.078405
...          ...       ...       ...
449995 -0.668052 -1.045854 -1.307245
449996 -0.688457 -1.063332 -1.323172
449997 -0.668052 -1.045854 -1.307245
449998 -0.627243 -1.010898 -1.275391
449999 -0.586434 -0.975941 -1.243537

[450000 rows x 3 columns]


In [21]:
n = np.size(data,0)					#Rows					# Number of points in the dataset
d = np.size(data,1)         #Columns
print(n)
print(d)

450000
3


In [22]:
k = 17													# Number of clusters (say k = 17)
Sample_size = 100										# Desired coreset size (say m = 100)


def D2(data, k):
    # Initialize B with one random point from data
    B = [data[np.random.choice(range(n))]]
    for _ in range(1, k):
        print("Current k is ", k)
        # Calculate the distance from each point in data to the set B
        distances = np.min(cdist(data, B, 'euclidean')**2, axis=1)
        print("Distances",distances)
        # Calculate the probabilities for each point
        probabilities = distances / np.sum(distances)
        print("Probabilities",probabilities)
        # Sample a new point based on the calculated probabilities
        B.append(data[np.random.choice(range(n), p=probabilities)])
        print("B",B)
    return np.array(B)

In [23]:
B = D2(data,k)

Current k is  17
Distances [9.25635671 8.88440939 6.6569743  ... 0.13107891 0.14975695 0.17623898]
Probabilities [3.22870972e-06 3.09897078e-06 2.32201916e-06 ... 4.57216347e-08
 5.22367203e-08 6.14739186e-08]
B [array([-0.933311  , -1.15072309, -1.08426674]), array([1.63765691, 1.05152498, 0.92253737])]
Current k is  17
Distances [1.06488516 1.18458976 2.15289212 ... 0.13107891 0.14975695 0.17623898]
Probabilities [1.01173903e-06 1.12546943e-06 2.04544589e-06 ... 1.24537045e-07
 1.42282901e-07 1.67443274e-07]
B [array([-0.933311  , -1.15072309, -1.08426674]), array([1.63765691, 1.05152498, 0.92253737]), array([-1.64746876, -0.15446801,  1.79852329])]
Current k is  17
Distances [1.06488516 1.18458976 2.15289212 ... 0.13107891 0.14975695 0.17623898]
Probabilities [1.22683865e-06 1.36474857e-06 2.48031558e-06 ... 1.51014102e-07
 1.72532794e-07 2.03042360e-07]
B [array([-0.933311  , -1.15072309, -1.08426674]), array([1.63765691, 1.05152498, 0.92253737]), array([-1.64746876, -0.15446801,  

In [24]:
print(B)

[[-0.933311   -1.15072309 -1.08426674]
 [ 1.63765691  1.05152498  0.92253737]
 [-1.64746876 -0.15446801  1.79852329]
 [-1.05573805 -1.48280812  0.73141317]
 [ 0.67864507 -0.08455537 -0.4790401 ]
 [-0.58643438 -0.08455537  0.54028897]
 [-0.74967044  1.22630657  1.78259628]
 [-0.23955776 -0.55646567 -0.65423729]
 [-1.38221016 -0.55646567 -0.36755099]
 [ 1.08673521  2.18760534  2.14891766]
 [ 0.45419549  0.73691811  0.22174863]
 [ 1.47442085  0.50970204  0.01469742]
 [-0.97412002 -1.34298284  0.26952968]
 [ 3.27001749  1.78560767  1.32071279]
 [-0.01510818 -0.43411856 -0.60645624]
 [ 0.04610534  0.98161234  0.572143  ]
 [-0.30077128 -0.85359438  0.79512124]]


In [25]:
print(pd.DataFrame(B))

           0         1         2
0  -0.933311 -1.150723 -1.084267
1   1.637657  1.051525  0.922537
2  -1.647469 -0.154468  1.798523
3  -1.055738 -1.482808  0.731413
4   0.678645 -0.084555 -0.479040
5  -0.586434 -0.084555  0.540289
6  -0.749670  1.226307  1.782596
7  -0.239558 -0.556466 -0.654237
8  -1.382210 -0.556466 -0.367551
9   1.086735  2.187605  2.148918
10  0.454195  0.736918  0.221749
11  1.474421  0.509702  0.014697
12 -0.974120 -1.342983  0.269530
13  3.270017  1.785608  1.320713
14 -0.015108 -0.434119 -0.606456
15  0.046105  0.981612  0.572143
16 -0.300771 -0.853594  0.795121


In [26]:
def Sampling(data, k, centers, Sample_size):
    # Calculate the distance from each point in data to the nearest center
    distances = np.min(cdist(data, centers, 'euclidean')**2, axis=1)
    phi = np.sum(distances) / len(data)
    
    # Calculate the sampling probabilities for each point
    probabilities = distances / phi
    
    # Normalize the probabilities
    probabilities /= np.sum(probabilities)
    
    # Sample points based on the calculated probabilities
    sample_indices = np.random.choice(len(data), size=Sample_size, p=probabilities)
    coreset = data[sample_indices]
    
    # Calculate the weights for the sampled points
    weight = 1 / (Sample_size * probabilities[sample_indices])
    
    return coreset, weight


In [27]:
# Assuming data and k are already defined earlier
# Failed - centers = np.random.rand(k, 2)  # Randomly initialized centers
centers = np.random.rand(k, data.shape[1])  # Randomly initialized centers with 37 columns
Sample_size = 100  # Desired coreset size

In [28]:
coreset, weight = Sampling(data, k, centers, Sample_size)
print("Coreset shape:", coreset.shape)
print("Weights:", weight)

Coreset shape: (100, 3)
Weights: [ 1726.53147609  1811.58563975  1282.52373297  2325.83765455
  1262.64909445  1731.40227355 22346.26262965  2619.1905372
  1209.26480356  1417.38734074  4780.40699669  1176.89522822
  1738.44242139  1149.77075354  1773.92528132  1169.0843094
  1156.59652631  2592.96381386  3152.23483011 15844.07470438
  1720.13698687  4287.83491346  3193.74448448  1238.63685423
  1631.42109133  1663.92931868  1352.35283756  2343.32716148
  1348.37665948  1729.82929291  1516.06383386  2171.12875338
  2519.2154012   5255.44846931  2261.92820322  1096.31261669
  1573.13111188  2581.36529084  1396.29330439  2559.59503316
  1819.60563001  5349.53295531  1573.13111188  4262.74353023
  1160.40226133  2073.1411747   1805.41221381  2442.38674879
  1472.40592145  1455.08576     3500.69053636  1801.82489158
  1770.99018301  2120.3597284   1161.82890883  2188.76114839
  1555.59364354  1915.93711909  1247.72219796  1314.59131135
  2149.02906847  3361.81932467  1273.27701752  3914.02

In [29]:
# Now Viewing Corset and Weights
print(pd.DataFrame(coreset))

           0         1         2
0  -0.892502 -1.220636 -1.450588
1  -0.708861  1.960389  2.180772
2  -1.198570 -1.430374 -1.673566
3   0.964308  2.554647  1.941866
4  -1.525042 -1.325505 -1.562077
..       ...       ...       ...
95 -0.851693 -1.168201 -1.434661
96 -1.545446 -1.744981 -0.463113
97 -1.259783 -0.346728 -1.004632
98 -0.423198  1.208828  0.763267
99 -1.300592 -1.640112 -0.797580

[100 rows x 3 columns]


In [30]:
# Weights
print(pd.DataFrame(weight))

               0
0    1726.531476
1    1811.585640
2    1282.523733
3    2325.837655
4    1262.649094
..           ...
95   1805.412214
96   1580.977237
97   2867.895821
98  10568.879137
99   1674.541641

[100 rows x 1 columns]
